### ISSUE TITLE
Choc .kicad_sym file not present in Untested branch?

### ISSUE THREAD

**Issue by fatihG** [ebastler/marbastlib#1]
I tried to add the library files to KiCad after following the instructions on how to add the submodule. 

After I did all the steps I was unable to locate the symbol library for the choc components. 
The MX and Various .kicad_sym files are present and I am able to add those to KiCad. 

Since I am planning on using chocs for my board, I figured using that library would be the easier option.

**Comment by ebastler** [comment]
The only symbol I have in the mx.kicad_sym is a symbol for the stabilizers - I usually just use generic kicad pushbotton symbols for key switches, that's why the chocs don't have a dedicated symbol lib.

**Comment by fatihG** [comment]
Makes sense. 

I am very noob to all this PCB stuff, I forgot you had to manually assign footprints to symbols.

**Comment by ebastler** [comment]
This has been addressed, together with some other issues, in today's patch. Thanks for pointing it out!
If you want to update to the latest lib:
`git submodule update --remote`, but watch out as it introduced some other changes as well (Mainly all hotswap and  reverse mount LED footprints are now flipped, and must manually be flipped back).
