### ISSUE TITLE
Question about Choc stabilizer footprint

### ISSUE THREAD

**Issue by ubikitty** [ebastler/marbastlib#17]
The choc stabilizer footprint cuts two holes in the pcb.
I would like to know what they are used for and if they are mandatory?

![image](https://github.com/ebastler/marbastlib/assets/28765701/85fbb7be-8e90-4339-a2ab-6ba1f9a01f46)

**Comment by ebastler** [comment]
Hi! The choc stabs themselves protrude through the PCB, so sadly they are mandatory. pretty annoying...

The big one is for the slider, can't remember what the small one is for. Probably the part holding the wire. 

Ah, one caveat: The slider is offcenter for some weird reason, that makes Choc stabilized keys directional. Can only put them on "the right way", if you rotate the caps 180° they won't fit anymore. If you wanna use any sculpted profile caps (I do not know of any that exist), the stab orientation on the PCB/plate will determine which way the cap fits...

**Comment by ubikitty** [comment]
Thank you very much for your answer and your insights on the quirks of the choc stabilizers! Did not notice that the stabilized keys were asymmetrical...

**Comment by ebastler** [comment]
Found 2 pics of a MBK 2u cap, maybe they are interesting for this topic.

![Untitled](https://github.com/ebastler/marbastlib/assets/22500643/8799c1f1-8091-4e23-a812-abefdbff3862)
