### ISSUE TITLE
MX_SW_solder & MX_SW_HS connector pin location difference

### ISSUE THREAD

**Issue by thoni56** [ebastler/marbastlib#20]
I tried to simply switch from MX_SW_solder to MX_SW_HS and was expecting to just do some minor adjustment of the wiring on the board. But it seems that the connector pins have "reversed" locations. Pin 1 is to the left in MX_SW_solder and to the right in MX_SW_HS.

I suggest making this the same would make changing from MX_SW_solder to MX_SW_HS much simpler.

**Comment by ebastler** [comment]
Hi!

This slightly weird choice of mine is based on how KiCad handles component assembly. In a footprint, KiCad always expects the part to be assembled on the top side. MX switches for solder footprints are assembled from the top, so solder pads on B.Cu. Hotswap sockets however are assembled from bottom on a keyboard, so I had to put the solder pads on F.Cu and expect the user to flip all hotswap footprints to the "other side" of the PCB after placing them on the PCB.

This is a slight nuisance, but in return all assembly files will be generated correctly without manual tinkering on files. It will have solder switches as topside THT assembly and hotswap sockets as bottom side SMD assembly.

If you made a PCB for solder footprints, then changed them to HS footprints, you'll have to flip all of them to the other side once, easiest way: press `h` and click on F.Cu in the sidebar to highlight your interactions on the front copper layer, then hover the mouse over a socket, press `f`to flip, and repeat once for all other sockets.

Courtyards of the footprints are correct - 14x14mm on front (where the switch sits) and slightly larger than the socket on the back (where the socket sits).
