### ISSUE TITLE
Seeeduino Xiao boards support?

### ISSUE THREAD

**Issue by idesignstuff** [ebastler/marbastlib#22]
The Xiao (especially the NRF52840 "BLE" version) boards are an increasingly popular choice for split wireless ZMK keebs. Would you be willing to add them to your footprints/symbols library? 
https://wiki.seeedstudio.com/XIAO_BLE/#resources

**Comment by ebastler** [comment]
Hi!

I was planning to extend the promicorish lib and add (among others) xiao, but did not find the time for it so far - I mostly focused on footprints I needed myself recently as I was short on time.

Can't give any proper ETA, but it is planned :)

**Comment by idesignstuff** [comment]
Thanks for considering it!

**Comment by ebastler** [comment]
I'm currently beginning to work on them - if you have any recommendations on how to handle the bottom pads... This is a Xiao BLE, will also make a xiao rp2040 and maybe esp32 later on. 

I know that on BLE you need the bottom pads for both flashing and battery. I will make a SMD only version (-> solder paste covered SMD pads, for reflow), but not quite sure how to handle them for THT and combo footprints...

![image](https://github.com/ebastler/marbastlib/assets/22500643/f36eb8d0-10ea-42ad-b90b-df12368bc752)
