### ISSUE TITLE
Wrong Pin numbers for MX_SK6812MINI-E Symbol

### ISSUE THREAD

**Issue by Bob837217** [ebastler/marbastlib#23]
According to the datasheet copy hosted at: https://datasheet.lcsc.com/lcsc/2305101623_OPSCO-Optoelectronics-SK6812MINI-E_C5149201.pdf
This was last edited on 2021-04-07 with revision "A/O"

Here is the pinout from that PDF:
![image](https://github.com/ebastler/marbastlib/assets/68859866/1aa1af1f-714a-4235-baf6-a484da203ada)

Here is the Symbol pinout as seen in KiCAD 7.0.6:
![image](https://github.com/ebastler/marbastlib/assets/68859866/16d063cd-59a2-45cd-a67d-17032025a57f)

```
PDF Pinout Numbers:
VDD:    1
DOUT:   2
GND:    3
DIN:    4

Symbol Pinout Numbers:
VDD:    1
DOUT:   2
DIN:    3
GND:    4
```

Symbol uses "VSS", but to my knowledge that means "GND".
So you can see that pins 3,4 are mismatched between the two.

**Comment by ebastler** [comment]
Hi, this has been done for a reason - the footprint is shared between 2 LEDs with different pin numberings, so the symbol does not follow datasheet numbering, but footprint numbering.

If you compare the 6028 footprint, you will notice it deviates from the datasheet, but in the end the different numbering on symbol and footprint results in a correct pinout - these have been tested.

**Comment by Bob837217** [comment]
Ok, thanks for the explanation.  I will mark this as closed.
