### ISSUE TITLE
SK6812 mini-e wrong pinout

### ISSUE THREAD

**Issue by Trecoolius** [ebastler/marbastlib#33]
Pins 3 and 4 are swapped, I just lost $100 to this.

**Comment by ebastler** [comment]
Hi,

Sorry for your issues. Which symbol did you use? The ones included in this library account for the swapped pins and works.

This originates in the fact that the footprint was originally made for a different passive RGB LED, and then re-used for MINI-E but kept the pin numbering of the old LED. I have used 3 LEDs with different pin numbers with the same footprint by now, symbols taking care of the pinouts.

As long as you used one of the MINI-E symbols from marbastlib, the wrong pin order is not your issue. This combination has been prototyped and used for production on countless boards.
