### ISSUE TITLE
DIODE

### ISSUE THREAD

**Issue by Finnitio** [ebastler/marbastlib#36]
Hey,

I was wondering if adding a standard diode would be helpful? Just spent some time to research which to use and find the correct ones for ergo mech keyboards. I suppose the smd handsolder ones are 1N4148W aswell? Couldn't relly find a footprint and now I need to get to bed ;). Thanks for the library.

**Comment by ebastler** [comment]
Hi! We only add footprints and/or symbols to this lib that either do not exist in KiCad default libs already, or which we believe we can improve in any significant way over the deafault ones. SOD-123, SOD-323 and SOD-523 footprints from the base libs are, in my opinion, perfect as they are, so not planned to include them to the lib.

Regarding your issues - `1N4148W` do not have any dedicated footprint in KiCad libs, as they use a common SOD-123 footprint, shared with many other diodes. That one is part of KC base libs. You can find `1N4148W` in the KiCad symbols library, and it will automatically assign the correct footprint to the symbol from the base libs.
