### ISSUE TITLE
Missing footprint for IS313741A

### ISSUE THREAD

**Issue by joelspadin** [ebastler/marbastlib#5]
The symbol for IS313741A uses footprint `marbastlib-various:QFN-60_EP_7x7_Pitch0.4mm`, but no such footprint exists.

**Comment by ebastler** [comment]
That footprint hasn't been tested yet, hence it is only available on the `untested` branch. 

I gave up having symbols split in tested and untested, since that is annoying to maintain with kicad sym libs. Symbols are all in all libs, footprints are separated into the branches.

**Comment by joelspadin** [comment]
Ah, okay.
